Repository googleapis/nodejs-analytics-admin, pull requests merged in 2020-07, with the labels that each got.

#7 build: system tests were not configured
  .kokoro/presubmit/node10/common.cfg
  synth.metadata
Labels: cla: yes

#10 feat: add samples
  package.json
  samples/package.json
  samples/quickstart.js
  samples/quickstart_installed_oauth2.js
  samples/quickstart_service_account.js.js
  samples/test/quickstarts.js
Labels: cla: yes

#11 fix: broken docs test
  linkinator.config.json
Labels: cla: yes

#8 build: move gitattributes
  .gitattributes
  synth.metadata
Labels: cla: yes, context: none

#19 chore: update broken doc link
  .kokoro/release/docs-devsite.cfg
  .repo-metadata.json
  README.md
  linkinator.config.json
  samples/README.md
  synth.metadata
Labels: cla: yes

#18 chore(node): fix kokoro build path for cloud-rad
  protos/protos.d.ts
  protos/protos.js
Labels: cla: yes, context: partial
