Repository googleapis/nodejs-analytics-admin, pull requests merged in 2020-08, with the labels that each got.

#13 fix: samples and tests updated
  samples/package.json
  samples/quickstart.js
  samples/quickstart_installed_oauth2.js
  system-test/analyticsadmin.ts
Labels: cla: yes

#21 fix(docs): update docs with current samples
  README.md
  protos/protos.d.ts
  protos/protos.js
  samples/README.md
  synth.metadata
Labels: cla: yes

#22 build: update protos
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: none

#24 build: --credential-file-override is no longer required
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#25 build: use gapic-generator-typescript v1.0.7.
  src/v1alpha/analytics_admin_service_client.ts
  synth.metadata
Labels: automerge, cla: yes, context: full

#26 chore: update cloud rad kokoro build job
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#27 build: perform publish using Node 12
  .kokoro/release/publish.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#28 docs(samples): added documentation region tags
  samples/quickstart.js
Labels: cla: yes

#29 docs: updates to the readme
  README.md
  samples/README.md
  synth.metadata
Labels: cla: yes, context: none

#30 chore: start tracking obsolete files
  synth.metadata
Labels: automerge, cla: yes, context: full

#31 build: move system and samples test from Node 10 to Node 12
  .kokoro/continuous/node12/lint.cfg
  .kokoro/continuous/node12/samples-test.cfg
  .kokoro/continuous/node12/system-test.cfg
  .kokoro/presubmit/node12/samples-test.cfg
  .kokoro/presubmit/node12/system-test.cfg
  synth.metadata
Labels: api: analyticsadmin, cla: yes, context: full

#34 build: track flaky tests for "nightly", add new secrets for tagging
  .github/publish.yml
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: api: analyticsadmin, cla: yes, context: full
