Repository googleapis/nodejs-analytics-admin, pull requests merged in 2020-11, with the labels that each got.

#47 docs: updated code of conduct (includes update to actions)
  .github/workflows/ci.yaml
  .kokoro/release/docs-devsite.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: api: analyticsadmin, cla: yes, context: full

#48 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: analyticsadmin, automerge, cla: yes, context: full

#50 fix: do not modify options object, use defaultScopes
  package.json
  protos/google/analytics/admin/v1alpha/analytics_admin.proto
  protos/google/analytics/admin/v1alpha/resources.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/index.ts
  src/v1alpha/analytics_admin_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: analyticsadmin, automerge, cla: yes

#49 fix: 'requests' field of CreateUserLink, UpdateUserLink, DeleteUserLink methods is now required docs: minor documentation updates
  synth.metadata
Labels: api: analyticsadmin, automerge, cla: yes, context: full

#55 fix: do not modify options object, use defaultScopes docs: regenerated jsdoc comments with examples build: use gapic-generator-typescript v1.2.1
  protos/protos.json
  src/v1alpha/analytics_admin_service_client.ts
  synth.metadata
Labels: api: analyticsadmin, cla: yes, context: partial

#61 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: analyticsadmin, automerge, cla: yes, context: full
