Repository googleapis/nodejs-analytics-admin, pull requests merged in 2021-03, with the labels that each got.

#81 docs: add `https://www.googleapis.com/auth/analytics.edit` OAuth2 scope to the list of acceptable scopes for all read only methods of the Admin API docs: update the documentation of the `update_mask` field used by Update() methods
  protos/google/analytics/admin/v1alpha/analytics_admin.proto
  protos/google/analytics/admin/v1alpha/resources.proto
  src/v1alpha/analytics_admin_service_client.ts
  synth.metadata
Labels: api: analyticsadmin, cla: yes, context: full

#84 build: update gapic-generator-typescript to v1.2.10.
  synth.metadata
  webpack.config.js
Labels: api: analyticsadmin, automerge, cla: yes, context: full

#87 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .repo-metadata.json
  synth.metadata
  synth.py
Labels: api: analyticsadmin, cla: yes
